package au.edu.jcu.cp3406.foleyapp;

public enum Sound {
    CAT_MEOW, COW_MOO, DOG_BARK, DUCK_QUACK, ELEPHANT_TRUMPET, FROG_CROAK, GOOSE_CALL, HAWK_CALL, MOUNTAIN_LION_ROAR, PIG_SNORT, RATTLESNAKE_RATTLE, ROOSTER_CROW
}
